version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "buy-btc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ndq6t8947qei"
s3_prefix = "buy-btc"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
